services:
  - type: web
    name: pawberry-backend
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    preDeployCommand: npx prisma migrate deploy
    initialDeployHook: npm run seed
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: http://127.0.0.1:5173
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pawberry-db
          property: connectionString

databases:
  - name: pawberry-db
    databaseName: pawberry
    user: pawberry
    plan: basic-256mb
    region: singapore
